name: Target Teaching
description: Tim Carroll - Certified NRA pistol instructor
url: http://www.targetteaching.com
author: Tim Carroll
copyright: 2014 Tim Carroll All rights reserved
base_url: http://www.targetteaching.com
markdown: redcarpet
highlighter: rouge
paginate: 5
paginate_path: "page:num"
safe: false
plugins: _plugins
gems: [digest/md5,net/http]
lsi: false
enable_analytics: false